### ISSUE TITLE
[Feature Request] Geometry Shaders

### ISSUE THREAD

**Issue by sabjorn** [leadedge/ShaderMaker#6]
Is it possible to implement the use of Geometry Shaders?

It would be nifty to be able to generate structures from input video frames (e.g. point clouds!)

**Comment by leadedge** [comment]
Since this plugin is written to support the ShaderToy concept of a fragment shader, a fixed set of uniform variables and a fixed vertex shader, I don't think it is possible directly without departing from ShaderToy compatibility. I don't know much about geometry shaders,  but there's nothing preventing you from experimenting. I suspect that  modification of the vertex shader would be possible. This would depart from the ShaderToy compatibility but it's worth trying.
