### ISSUE TITLE
Resolume 6?

### ISSUE THREAD

**Issue by DanielArnett** [leadedge/ShaderMaker#7]
Has anyone tested this with Resolume 6 yet? I keep getting spammed on forums asking to make my shaders work with Resolume 6. I also get asked to make them 64 bit, but I don't see why that would make a difference.

**Comment by leadedge** [comment]
Hi Daniel,

Sorry that you are getting spammed. Resolume 6 is now 64 bit and 32 bit plugins won't work with it. Hence the requests.

In theory you should be able to compile 64  bit because FFGL 1.6 supports it. But I have not revisited this project for some time and have not tested it thoroughly because I am in the process of completing another project that will hopefully replace it.

It seems to work OK with all the shaders I have, so I tried yours by extracting them from the source code. Only flat-to-fisheye works. The others crash for reasons unknown. I will try to find out why. 

Meanwhile, if you like, please contact me via the email on the Spout home page and perhaps we can nail this down. I have found a strange problem with another 360 shader that works OK 32 bit but not 64 bit and you might have some insight on that.

**Comment by DanielArnett** [comment]
Oh great, thanks for checking that for me! I'll also update my Resolume so
I can test as well. I've seen some interesting quirks that cause problems
on Mac but not Windows (like using vec4 or atan() if I recall correctly),
maybe some of those also carry on to this as well.

**Comment by leadedge** [comment]
I found the problem that caused the crash. Nothing to do with your shaders. Also I can't reproduce the trouble I was having before with the other 360 shader. If you are interested, please feel free to contact me in any case.

**Comment by joniose** [comment]
i have a similar problem. All Shaders i want to compile wont work.
Also not the included project.
@leadedge when will the new project be ready?

**Comment by DanielArnett** [comment]
Could you link to an example you want to compile?

**Comment by joniose** [comment]
https://icfmuenchen-my.sharepoint.com/:f:/g/personal/jonathan_osenberg_icf-muenchen_de/EuVzjM6gJD9Hn7xuhB9d6VkBxo2iYovtvzqDBaRwnCPMyg?e=fgPq5p

**Comment by joniose** [comment]
I solved it.
It was the x64 Problem. i changed the Output to it und now it works 😍.

**Comment by DanielArnett** [comment]
Nice.
